In [1]:
"""
神经网络的定义方式，获取参数，保存参数
"""

'\n神经网络的定义方式，获取参数，保存参数\n'

In [2]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
%run read_fashion_image.ipynb

x_train, y_train, x_test, y_test = get_data()

In [4]:
x_train = x_train / 255.0
x_test = x_test / 255.0

In [5]:
x_train = np.array([x.reshape(28,28) for x in x_train ])
x_test = np.array([x.reshape(28,28) for x in x_test ])

In [5]:
# 方式1：一次性定义全部网络结构
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Flatten(input_shape=(28, 28)),
                                    tf.keras.layers.Dense(256, activation='relu',),
                                    tf.keras.layers.Dense(10, activation='softmax')
                                    ])

In [48]:
# 方式2：以序列方式定义，分别定义每一层
def MLP():
    flatten_layer = tf.keras.layers.Flatten()
    def dense_layer(name):
        return tf.keras.layers.Dense(256, activation=tf.nn.relu, name=name)
    dropout_layer = tf.keras.layers.Dropout(0.5)
    output_layer = tf.keras.layers.Dense(10, activation='softmax')

    model = tf.keras.models.Sequential()
    model.add(flatten_layer)
    for i in range(2):
        model.add(dense_layer("dense%d" % i)) # 每一层起不同的名字
        model.add(dropout_layer)
    model.add(output_layer)
    return model
    
model = MLP()
type(model)

tensorflow.python.keras.engine.sequential.Sequential

In [66]:
# 方式3：以类的方式定义，更工程化
class MLP1(tf.keras.Model):
    
    def __init__(self):
        super().__init__()
        self.flatten_layer = tf.keras.layers.Flatten()
        self.dense_layer = tf.keras.layers.Dense(256, activation=tf.nn.relu)
        self.dropout_layer = tf.keras.layers.Dropout(0.5)
        self.output_layer = tf.keras.layers.Dense(10, activation='softmax')
        
    def call(self, inputs, training=False):
        x = self.flatten_layer(inputs)
        x = self.dense_layer(x)
        x = self.dense_layer(x)
#         for i in range(2):
#             x = self.dense_layer(x)
#             if training:
#                 x = self.dropout_layer(x, training=training)
#         x = self.dense_layer(x)
#         x = self.dropout_layer(x)
#         x = self.dense_layer(x)
#         x = self.dropout_layer(x)
        output = self.output_layer(x)     
        return output
    
model = MLP1()
type(model)

__main__.MLP1

In [67]:
model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.5),
             loss = 'sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [68]:
model.fit(x_train, 
          y_train, 
          epochs=5,
          batch_size=256
          )

    def call(self, inputs, training=False):
        x = self.flatten_layer(inputs)
        x = self.dense_layer(x)
        x = self.dense_layer(x)
#         for i in range(2):
#             x = self.dense_layer(x)
#             if training:
#                 x = self.dropout_layer(x, training=training)
#         x = self.dense_layer(x)
#         x = self.dropout_layer(x)
#         x = self.dense_layer(x)
#         x = self.dropout_layer(x)
        output = self.output_layer(x)     
        return output

This may be caused by multiline strings or comments not indented at the same level as the code.
    def call(self, inputs, training=False):
        x = self.flatten_layer(inputs)
        x = self.dense_layer(x)
        x = self.dense_layer(x)
#         for i in range(2):
#             x = self.dense_layer(x)
#             if training:
#                 x = self.dropout_layer(x, training=training)
#         x = self.dense_layer(x)
#         x = self.dropout_layer(x)
#         x = self.d

ValueError: in converted code:

    <ipython-input-66-6bfd99501c30>:14 call
        x = self.dense_layer(x)
    /anaconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:812 __call__
        self.name)
    /anaconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/input_spec.py:213 assert_input_compatibility
        ' but received input with shape ' + str(shape))

    ValueError: Input 0 of layer dense_33 is incompatible with the layer: expected axis -1 of input shape to have value 784 but received input with shape [None, 256]


In [63]:
model.fit(x_train, 
          y_train, 
          epochs=5,
          batch_size=256,
          validation_data=(x_test, y_test),
          validation_freq=1)

    def call(self, inputs, training=False):
        x = self.flatten_layer(inputs)
        x = self.dense_layer(x)
        x = self.dense_layer(x)
#         for i in range(2):
#             x = self.dense_layer(x)
#             if training:
#                 x = self.dropout_layer(x, training=training)
#         x = self.dense_layer(x)
#         x = self.dropout_layer(x)
#         x = self.dense_layer(x)
#         x = self.dropout_layer(x)
        output = self.output_layer(x)     
        return output

This may be caused by multiline strings or comments not indented at the same level as the code.
    def call(self, inputs, training=False):
        x = self.flatten_layer(inputs)
        x = self.dense_layer(x)
        x = self.dense_layer(x)
#         for i in range(2):
#             x = self.dense_layer(x)
#             if training:
#                 x = self.dropout_layer(x, training=training)
#         x = self.dense_layer(x)
#         x = self.dropout_layer(x)
#         x = self.d

ValueError: in converted code:

    <ipython-input-61-308e44d85a54>:14 call
        x = self.dense_layer(x)
    /anaconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py:812 __call__
        self.name)
    /anaconda3/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/input_spec.py:213 assert_input_compatibility
        ' but received input with shape ' + str(shape))

    ValueError: Input 0 of layer dense_31 is incompatible with the layer: expected axis -1 of input shape to have value 784 but received input with shape [None, 256]


In [26]:
model.fit(x_train, 
          y_train, 
          epochs=5,
          batch_size=256,
          validation_data=(x_test, y_test),
          validation_freq=1)

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 2s 33us/sample - loss: 0.8518 - accuracy: 0.6862 - val_loss: 0.6812 - val_accuracy: 0.7404
Epoch 2/5
60000/60000 [==============================] - 2s 26us/sample - loss: 0.5453 - accuracy: 0.7964 - val_loss: 0.5147 - val_accuracy: 0.8201
Epoch 3/5
60000/60000 [==============================] - 2s 25us/sample - loss: 0.4900 - accuracy: 0.8190 - val_loss: 0.4907 - val_accuracy: 0.8236
Epoch 4/5
60000/60000 [==============================] - 2s 26us/sample - loss: 0.4499 - accuracy: 0.8349 - val_loss: 0.4865 - val_accuracy: 0.8114
Epoch 5/5
60000/60000 [==============================] - 1s 25us/sample - loss: 0.4250 - accuracy: 0.8426 - val_loss: 0.4163 - val_accuracy: 0.8405


## 获取每一层的权重系数

In [65]:
len(model.weights)

6

In [66]:
model.weights[0]

<tf.Variable 'sequential_6/dense0/kernel:0' shape=(784, 256) dtype=float32, numpy=
array([[ 0.04358891, -0.05935635,  0.04191222, ...,  0.05466488,
        -0.00254817,  0.01894611],
       [-0.03180718,  0.05504592, -0.06065722, ...,  0.02531308,
         0.00610358, -0.01886529],
       [ 0.06975316, -0.06416669, -0.0189217 , ..., -0.06338106,
         0.07242534,  0.02792194],
       ...,
       [-0.01122555,  0.03993281, -0.04979655, ..., -0.02200262,
         0.01217559,  0.03844057],
       [-0.06139922,  0.0655123 , -0.01436131, ..., -0.05383282,
         0.06556807,  0.05354907],
       [-0.03813687,  0.03930613,  0.01196447, ..., -0.01439606,
         0.06761973, -0.06534402]], dtype=float32)>

In [67]:
model.weights[1]

<tf.Variable 'sequential_6/dense0/bias:0' shape=(256,) dtype=float32, numpy=
array([-1.64143089e-02, -3.06452531e-02,  2.10800245e-02,  7.25917285e-03,
       -6.10000174e-03,  5.91970161e-02,  5.28772846e-02,  5.55351824e-02,
        1.29053593e-01, -4.09180447e-02,  1.22091519e-02,  1.07123189e-01,
        8.99421144e-03,  2.33754218e-01, -4.43066396e-02, -1.44509338e-02,
       -2.71365047e-02,  1.11449905e-01, -1.79233830e-02, -1.60933226e-01,
        1.51089476e-02,  2.29997918e-01,  1.90238431e-02, -2.29381560e-03,
        9.67024118e-02, -6.61122100e-03,  4.08737622e-02, -2.50958055e-02,
       -2.32944284e-02,  1.43720778e-02,  9.16180387e-03,  2.50004735e-02,
        1.33906044e-02,  5.90289757e-02, -1.51758492e-01, -2.25578761e-03,
       -1.30756885e-01, -2.02967715e-03,  5.73362559e-02,  1.08117436e-03,
       -6.08546368e-04, -4.22387309e-02,  1.43802568e-01,  1.03909791e-01,
        1.70647532e-01,  3.40869606e-01, -7.56302103e-02,  1.29021600e-01,
        1.29899561e-01,

In [68]:
model.weights[2]

<tf.Variable 'sequential_6/dense1/kernel:0' shape=(256, 256) dtype=float32, numpy=
array([[-0.02766217,  0.03732958, -0.08450466, ...,  0.01432702,
        -0.07911391,  0.02257321],
       [-0.06539106, -0.10576568,  0.0250215 , ..., -0.06986461,
        -0.08995315,  0.02492773],
       [ 0.07400792, -0.10849069,  0.05458679, ..., -0.09829598,
        -0.0128841 , -0.00713505],
       ...,
       [-0.09862264, -0.06201045, -0.04176588, ..., -0.06321128,
        -0.07110613, -0.0048173 ],
       [-0.01109714, -0.07586544, -0.09420383, ...,  0.10271026,
         0.0373575 , -0.03779222],
       [ 0.06439859, -0.00620481,  0.07330702, ...,  0.09659082,
         0.0408005 , -0.07447951]], dtype=float32)>

In [69]:
model.weights[3]

<tf.Variable 'sequential_6/dense1/bias:0' shape=(256,) dtype=float32, numpy=
array([-3.42499204e-02,  1.27566978e-01,  1.13002099e-01, -4.76772450e-02,
        1.30573869e-01, -2.25142110e-02,  1.13083623e-01,  9.32680592e-02,
        2.66100783e-02,  1.87443882e-01,  4.39047907e-03,  1.71451285e-01,
        1.34939030e-01, -2.09078826e-02, -1.66190118e-02, -1.14746112e-02,
        1.28116786e-01,  4.21935767e-02,  4.36974056e-02,  5.52491993e-02,
        9.27499682e-02,  1.60301160e-02,  2.26601154e-01,  1.59883033e-02,
       -3.56972590e-02,  9.48188733e-03,  2.37283245e-01, -4.87253107e-02,
       -2.16226876e-02, -4.65673022e-02, -4.51437980e-02,  1.61715329e-01,
        3.78791317e-02, -4.60289083e-02,  1.13930240e-01,  8.81216004e-02,
        1.02559887e-01,  3.13949548e-02, -3.05244327e-02, -4.55821166e-04,
        3.80917005e-02,  3.70457470e-02,  6.57953415e-03, -1.27722770e-02,
        1.90458938e-01,  9.79682580e-02,  4.37377095e-02,  1.54334769e-01,
        1.48185149e-01,

In [70]:
model.weights[4]

<tf.Variable 'sequential_6/dense_14/kernel:0' shape=(256, 10) dtype=float32, numpy=
array([[-0.11226083, -0.0979874 , -0.03733522, ...,  0.2446965 ,
        -0.12963848,  0.26193267],
       [ 0.15002106, -0.10534374, -0.06269068, ..., -0.1178015 ,
        -0.18511565, -0.08772626],
       [ 0.154404  ,  0.0402348 , -0.1594996 , ...,  0.06548733,
        -0.07345035, -0.12319739],
       ...,
       [-0.12877622, -0.06618959, -0.23317517, ...,  0.46487254,
         0.01301841,  0.36370137],
       [ 0.0692012 ,  0.02984063, -0.09269484, ..., -0.04543467,
        -0.07462528,  0.00701786],
       [-0.01948133, -0.12905468,  0.37550774, ..., -0.00858693,
        -0.10251138, -0.17401764]], dtype=float32)>

In [71]:
model.weights[5]

<tf.Variable 'sequential_6/dense_14/bias:0' shape=(10,) dtype=float32, numpy=
array([ 0.05210388, -0.42345208,  0.55860037,  0.24357876, -0.2022633 ,
        0.10888381,  0.62025636, -0.08870672, -0.06511167, -0.80388385],
      dtype=float32)>

In [ ]:
"""
问题：搞清楚单层全连接神经网络的权重系数有多少，矩阵结构是怎样的。
  比如：同一层里的多个神经元，bias有多少个，每个神经元都不同还是共享的？明显是不共享的。
  
为什么输出的weights要么只有bias，要么只有系数？ 不是应该两者同时都有吗？
答：要给每个layer设置name参数，这样weights就不会被覆盖写，否则，相同name的weights只会记录一份。

  
"""