In [1]:
"""
另一种神经网络的定义方式，更加灵活
"""

'\n另一种神经网络的定义方式，更加灵活\n'

In [2]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
%run read_fashion_image.ipynb

x_train, y_train, x_test, y_test = get_data()

In [4]:
x_train = x_train / 255.0
x_test = x_test / 255.0

In [5]:
x_train = np.array([x.reshape(28,28) for x in x_train ])
x_test = np.array([x.reshape(28,28) for x in x_test ])

In [5]:
# 方式1：一次性定义全部网络结构
# model = tf.keras.models.Sequential([
#                                     tf.keras.layers.Flatten(input_shape=(28, 28)),
#                                     tf.keras.layers.Dense(256, activation='relu',),
#                                     tf.keras.layers.Dense(10, activation='softmax')
#                                     ])

In [21]:
# 方式2：分别定义每一层，然后拼接起来
flatten_layer = tf.keras.layers.Flatten()
dense_layer = tf.keras.layers.Dense(256,activation=tf.nn.relu)
dropout_layer = tf.keras.layers.Dropout(0.5)
output_layer = tf.keras.layers.Dense(10, activation='softmax')

model = tf.keras.models.Sequential()
model.add(flatten_layer)
for i in range(3):  # 定义多层
    model.add(dense_layer) 
#     model.add(dropout_layer)
model.add(output_layer)

In [22]:
model.compile(optimizer=tf.keras.optimizers.SGD(lr=0.5),
             loss = 'sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [23]:
model.fit(x_train, 
          y_train, 
          epochs=5,
          batch_size=256,
          validation_data=(x_test, y_test),
          validation_freq=1)

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 1s 24us/sample - loss: 0.7920 - accuracy: 0.7121 - val_loss: 0.5971 - val_accuracy: 0.7891
Epoch 2/5
60000/60000 [==============================] - 1s 19us/sample - loss: 0.4790 - accuracy: 0.8235 - val_loss: 0.5641 - val_accuracy: 0.7755
Epoch 3/5
60000/60000 [==============================] - 1s 17us/sample - loss: 0.4202 - accuracy: 0.8439 - val_loss: 0.5993 - val_accuracy: 0.7819
Epoch 4/5
60000/60000 [==============================] - 1s 18us/sample - loss: 0.3863 - accuracy: 0.8569 - val_loss: 0.4588 - val_accuracy: 0.8365
Epoch 5/5
60000/60000 [==============================] - 1s 18us/sample - loss: 0.3599 - accuracy: 0.8670 - val_loss: 0.5282 - val_accuracy: 0.8090


## 获取每一层的权重系数

In [24]:
len(model.weights)

4

In [25]:
model.weights[0]

<tf.Variable 'sequential_2/dense_4/kernel:0' shape=(784, 256) dtype=float32, numpy=
array([[-0.01326577,  0.05353743, -0.04613684, ...,  0.01512438,
        -0.05713975,  0.01790981],
       [-0.07171859,  0.06371883, -0.01333776, ..., -0.03662582,
        -0.02242934, -0.01900315],
       [ 0.01364677, -0.06831619,  0.05898945, ...,  0.07483419,
        -0.05738248,  0.05306685],
       ...,
       [ 0.09154403, -0.00042456,  0.01787029, ...,  0.0581831 ,
        -0.05831866, -0.04562314],
       [-0.02809519,  0.01002197,  0.0615252 , ...,  0.00797478,
         0.04221744, -0.06172889],
       [ 0.06210614, -0.01971073, -0.05416953, ...,  0.00129098,
        -0.01843722,  0.02099417]], dtype=float32)>

In [26]:
model.weights[1]

<tf.Variable 'sequential_2/dense_4/bias:0' shape=(256,) dtype=float32, numpy=
array([ 2.25194424e-01,  9.12200361e-02, -1.79271977e-02,  9.82341263e-03,
        1.96356207e-01,  7.10925041e-03, -1.94994006e-02,  2.36009568e-01,
       -1.71681680e-02,  2.13983998e-01,  3.89741594e-03,  6.11486137e-02,
        1.12819761e-01,  2.64252275e-02,  2.33323306e-01, -2.25002952e-02,
       -8.89730547e-03, -2.24080291e-02,  6.85313046e-02, -4.29421626e-02,
        4.05995280e-01,  1.68659136e-01,  1.71183929e-01,  2.29118094e-02,
       -1.44290077e-02,  1.05158076e-01, -7.06093619e-03,  2.82583296e-01,
       -6.91402704e-03, -4.64737527e-02,  1.12297870e-02,  4.96082800e-03,
        4.50371087e-01, -3.88799906e-02, -4.65038158e-02,  2.53632933e-01,
       -1.33890575e-02, -2.40896512e-02, -2.76312903e-02,  1.07261933e-01,
        2.51288533e-01, -4.90944320e-03, -1.61959156e-02,  3.54464911e-02,
        1.88793436e-01,  7.96761215e-02, -2.56161422e-01, -1.43016595e-02,
       -3.48973796e-02

In [27]:
model.weights[2]

<tf.Variable 'sequential_2/dense_5/kernel:0' shape=(256, 10) dtype=float32, numpy=
array([[ 0.05432512,  0.01498794,  0.09378192, ..., -0.1876249 ,
        -0.07095113, -0.17087524],
       [ 0.00190415, -0.01344071, -0.13024068, ...,  0.19746   ,
        -0.13357083, -0.10201047],
       [-0.13553594, -0.04623799, -0.05481066, ...,  0.00581059,
         0.09365296,  0.02398786],
       ...,
       [ 0.10229769,  0.0826378 ,  0.19589181, ..., -0.07738955,
         0.00498028,  0.08767297],
       [-0.24684298, -0.13207583, -0.12355854, ...,  0.4500315 ,
         0.15153515,  0.30499202],
       [-0.00356028,  0.20399103, -0.07866155, ...,  0.10010336,
        -0.03496625, -0.10190053]], dtype=float32)>

In [28]:
model.weights[3]

<tf.Variable 'sequential_2/dense_5/bias:0' shape=(10,) dtype=float32, numpy=
array([ 0.19531798, -0.687023  ,  0.59054476,  0.36306056, -0.17690893,
        0.22684103,  0.95620215, -0.20429975, -0.1283199 , -1.135409  ],
      dtype=float32)>

In [ ]:
"""
问题：搞清楚单层全连接神经网络的权重系数有多少，矩阵结构是怎样的。
  比如：同一层里的多个神经元，bias有多少个，每个神经元都不同还是共享的？明显是不共享的。
  
为什么输出的weights要么只有bias，要么只有系数？ 不是应该两者同时都有吗？
  
"""