In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import backend as f
import numpy as np
import math
import sys
import time
sys.path.append("..") 
import d2lzh_tensorflow2 as d2l



In [2]:
(corpus_indices, char_to_idx, idx_to_char, vocab_size) = d2l.load_data_jay_lyrics(
    "../data/jaychou_lyrics.txt.zip")

In [3]:
corpus_indices

[611,
 495,
 245,
 223,
 256,
 222,
 338,
 611,
 495,
 91,
 265,
 795,
 59,
 550,
 638,
 435,
 338,
 611,
 495,
 91,
 265,
 322,
 754,
 993,
 457,
 271,
 338,
 322,
 754,
 993,
 550,
 638,
 907,
 338,
 35,
 920,
 847,
 920,
 847,
 920,
 847,
 993,
 611,
 611,
 611,
 611,
 216,
 265,
 338,
 20,
 76,
 950,
 194,
 183,
 338,
 696,
 35,
 717,
 886,
 564,
 643,
 884,
 864,
 819,
 338,
 232,
 290,
 839,
 736,
 1009,
 347,
 338,
 696,
 35,
 629,
 59,
 265,
 338,
 340,
 680,
 950,
 696,
 35,
 55,
 197,
 950,
 710,
 298,
 309,
 870,
 338,
 283,
 625,
 950,
 696,
 35,
 736,
 400,
 950,
 710,
 298,
 309,
 870,
 338,
 286,
 484,
 950,
 696,
 35,
 232,
 531,
 950,
 710,
 298,
 309,
 870,
 338,
 315,
 315,
 950,
 696,
 35,
 796,
 365,
 950,
 710,
 298,
 309,
 870,
 338,
 315,
 315,
 950,
 696,
 35,
 796,
 365,
 950,
 710,
 298,
 309,
 870,
 338,
 340,
 680,
 950,
 696,
 35,
 55,
 197,
 950,
 710,
 298,
 309,
 870,
 338,
 283,
 625,
 950,
 696,
 35,
 736,
 400,
 950,
 710,
 298,
 309,
 870,
 338,
 28

In [4]:
char_to_idx

{'留': 0,
 '板': 1,
 '烧': 2,
 '无': 3,
 '擅': 4,
 '碗': 5,
 '晚': 6,
 '二': 7,
 '妙': 8,
 '酋': 9,
 '寂': 10,
 '进': 11,
 '偷': 12,
 '胸': 13,
 '敢': 14,
 '是': 15,
 '东': 16,
 '好': 17,
 '宠': 18,
 '蝶': 19,
 '这': 20,
 '祈': 21,
 '恍': 22,
 '路': 23,
 '几': 24,
 '寄': 25,
 '昏': 26,
 '诉': 27,
 '镇': 28,
 '枚': 29,
 '实': 30,
 '妈': 31,
 '御': 32,
 '爬': 33,
 '养': 34,
 '我': 35,
 '盘': 36,
 '泥': 37,
 '最': 38,
 '替': 39,
 '所': 40,
 '酿': 41,
 '客': 42,
 '细': 43,
 '碎': 44,
 '以': 45,
 '琴': 46,
 '传': 47,
 '阻': 48,
 '午': 49,
 '墙': 50,
 '区': 51,
 '们': 52,
 '唱': 53,
 '课': 54,
 '面': 55,
 '爸': 56,
 '必': 57,
 '造': 58,
 '到': 59,
 '比': 60,
 '哈': 61,
 '诅': 62,
 '庭': 63,
 '敌': 64,
 '苍': 65,
 '屉': 66,
 '假': 67,
 '蝠': 68,
 '了': 69,
 '鸠': 70,
 '狠': 71,
 '稀': 72,
 '映': 73,
 '街': 74,
 '祷': 75,
 '样': 76,
 '村': 77,
 '甩': 78,
 '血': 79,
 '娘': 80,
 '丁': 81,
 '图': 82,
 '神': 83,
 '怕': 84,
 '成': 85,
 '童': 86,
 '飘': 87,
 '方': 88,
 '砖': 89,
 '少': 90,
 '和': 91,
 '问': 92,
 '缝': 93,
 '火': 94,
 '做': 95,
 '又': 96,
 '步': 97,
 '朋': 98,
 '猎': 99,
 '西': 100,

In [5]:
idx_to_char

['留',
 '板',
 '烧',
 '无',
 '擅',
 '碗',
 '晚',
 '二',
 '妙',
 '酋',
 '寂',
 '进',
 '偷',
 '胸',
 '敢',
 '是',
 '东',
 '好',
 '宠',
 '蝶',
 '这',
 '祈',
 '恍',
 '路',
 '几',
 '寄',
 '昏',
 '诉',
 '镇',
 '枚',
 '实',
 '妈',
 '御',
 '爬',
 '养',
 '我',
 '盘',
 '泥',
 '最',
 '替',
 '所',
 '酿',
 '客',
 '细',
 '碎',
 '以',
 '琴',
 '传',
 '阻',
 '午',
 '墙',
 '区',
 '们',
 '唱',
 '课',
 '面',
 '爸',
 '必',
 '造',
 '到',
 '比',
 '哈',
 '诅',
 '庭',
 '敌',
 '苍',
 '屉',
 '假',
 '蝠',
 '了',
 '鸠',
 '狠',
 '稀',
 '映',
 '街',
 '祷',
 '样',
 '村',
 '甩',
 '血',
 '娘',
 '丁',
 '图',
 '神',
 '怕',
 '成',
 '童',
 '飘',
 '方',
 '砖',
 '少',
 '和',
 '问',
 '缝',
 '火',
 '做',
 '又',
 '步',
 '朋',
 '猎',
 '西',
 '仔',
 '髅',
 '铁',
 '袋',
 '啃',
 '吹',
 '圈',
 '放',
 '兮',
 '其',
 '倦',
 '给',
 '膀',
 '场',
 '空',
 '剩',
 '联',
 '窗',
 '暖',
 '愁',
 '烦',
 '土',
 '前',
 '太',
 '索',
 '莹',
 '呢',
 '抖',
 '骨',
 '山',
 '消',
 '初',
 '题',
 '长',
 '侬',
 '距',
 '属',
 '药',
 '荡',
 '装',
 '惹',
 '拥',
 '熬',
 '哼',
 '沼',
 '蜥',
 '彿',
 '殿',
 '器',
 '古',
 '证',
 '手',
 'J',
 '秋',
 '玫',
 '模',
 '蝪',
 '确',
 '些',
 '止',
 '颁',
 '塞',
 '道',
 '寻',
 '帅',
 '欢'

In [6]:
vocab_size

1027

### 构造一个含单隐藏层、隐藏单元个数为256的循环神经网络层

In [7]:
"""
time_major=True, 这个参数的解释在doc中没找到
如果去掉这个参数，rnn_layer的输入参数第一维就不是num_steps，
所以这个参数的含义是，输入张量的第一维是num_steps时间步数
"""

'\ntime_major=True, 这个参数的解释在doc中没找到\n如果去掉这个参数，rnn_layer的输入参数第一维就不是num_steps，\n所以这个参数的含义是，输入张量的第一维是num_steps时间步数\n'

In [8]:
num_hiddens = 256
cell=keras.layers.SimpleRNNCell(num_hiddens,kernel_initializer='glorot_uniform')
rnn_layer = keras.layers.RNN(cell,
                             time_major=True, # 含义在doc中没找到,其含义可能是
                             return_sequences=True,
                             return_state=True # state是每个rnn单元输出的隐藏层状态，用于下一个单元的输入
                            )

In [9]:
batch_size = 2
state = cell.get_initial_state(batch_size=batch_size,dtype=tf.float32) # 初始化的隐藏状态列表
state.shape

TensorShape([2, 256])

目标：用周杰伦的歌词训练一个歌词创作模型。

在训练中我们需要每次随机读取小批量样本和标签。

时序数据的一个样本通常包含连续的字符。假设时间步数为5，样本序列为5个字符，即“想”“要”“有”“直”“升”。

该样本的标签序列为这些字符分别在训练集中的下一个字符，即“要”“有”“直”“升”“机”。

这里`rnn_layer`的输入形状为(时间步数, 批量大小, 输入个数)。其中输入个数即one-hot向量长度（词典大小）。

`rnn_layer`作为Keras的`RNN`实例，在前向计算后会分别返回输出和隐藏状态，其中输出指的是隐藏层在各个时间步上计算并输出的隐藏状态，它们通常作为后续输出层的输入。需要强调的是，该“输出”本身并不涉及输出层计算，形状为(时间步数, 批量大小, 隐藏单元个数)。

而`RNN`实例在前向计算返回的隐藏状态指的是隐藏层在最后时间步的可用于初始化下一时间步的隐藏状态：当隐藏层有多层时，每一层的隐藏状态都会记录在该变量中；对于像长短期记忆这样的循环神经网络，该变量还会包含其他信息。

In [ ]:
"""
时间步数：即RNN里cell的数量
为什么输入包含 batch_size？batch_size表示的就是这个batch里有多少个样本，本质上就是 num_samples 
RNNmodel的inputs是什么？

"""

In [10]:
num_steps = 23
X = tf.random.uniform(shape=(num_steps, batch_size, vocab_size)) # num_steps是使用多少个RNNcell来构造模型
Y, state_new = rnn_layer(X, state)  # 因为batch_size是2，所以state_new长度是2
Y.shape, len(state_new), state_new[0].shape, state_new[1].shape
# 注意 Y的维度是(num_steps, batch_size, num_hidden) state_new的维度是 (batch_size, num_hidden)

(TensorShape([23, 2, 256]), 2, TensorShape([256]), TensorShape([256]))

In [11]:
Y[-1,:,:] == state_new # Y是每个时间点的输出集合在一起，state_new是最后一个时间点的输出

<tf.Tensor: id=368, shape=(2, 256), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True, 

In [12]:
# 定义model
class RNNModel(keras.layers.Layer):
    def __init__(self, rnn_layer, vocab_size, **kwargs):
        super(RNNModel, self).__init__(**kwargs)
        self.rnn = rnn_layer
        self.vocab_size = vocab_size
        self.dense = keras.layers.Dense(vocab_size)

    def call(self, inputs, state):
        # 将输入转置成(num_steps, batch_size)后获取one-hot向量表示 
        X = tf.one_hot(tf.transpose(inputs), self.vocab_size) # input是(batch_size, num_steps)维
        Y,state = self.rnn(X, state)
        # 全连接层会首先将Y的形状变成(num_steps * batch_size, num_hiddens)，它的输出
        # 形状为(num_steps * batch_size, vocab_size)
        output = self.dense(tf.reshape(Y,(-1, Y.shape[-1])))
        return output, state

    def get_initial_state(self, *args, **kwargs):
        return self.rnn.cell.get_initial_state(*args, **kwargs)

In [13]:
# 观察一下X和Y是什么
data_iter = d2l.data_iter_consecutive(corpus_indices, batch_size, num_steps)

for X,Y in data_iter:
    print(X)
    print(X.shape)
    print(Y)
    break

[[611 495 245 223 256 222 338 611 495  91 265 795  59 550 638 435 338 611
  495  91 265 322 754]
 [757 717  35 338 814 769 814 874 338  35 234  69  20 576 687 338 726 769
  726 874 338  96 355]]
(2, 23)
[[495 245 223 256 222 338 611 495  91 265 795  59 550 638 435 338 611 495
   91 265 322 754 993]
 [717  35 338 814 769 814 874 338  35 234  69  20 576 687 338 726 769 726
  874 338  96 355  69]]


In [17]:
Y.T.reshape((-1,))

array([495, 717, 245,  35, 223, 338, 256, 814, 222, 769, 338, 814, 611,
       874, 495, 338,  91,  35, 265, 234, 795,  69,  59,  20, 550, 576,
       638, 687, 435, 338, 338, 726, 611, 769, 495, 726,  91, 874, 265,
       338, 322,  96, 754, 355, 993,  69])

In [14]:
# one hot 的用法：把第一维的每个值展开成one hot的高维向量，新增的one hot维作为最后一维
tf.one_hot(tf.transpose(X), 10000)

<tf.Tensor: id=375, shape=(23, 2, 10000), dtype=float32, numpy=
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)>

In [15]:
# 预测：给定开头的一个字，利用rnn，逐个输出后边的N个字
def predict_rnn_keras(prefix, num_chars, model, vocab_size, idx_to_char,
                      char_to_idx):
    # 使用model的成员函数来初始化隐藏状态
    state = model.get_initial_state(batch_size=1,dtype=tf.float32)
    output = [char_to_idx[prefix[0]]]
    #print("output:",output)
    for t in range(num_chars + len(prefix) - 1):
        X = np.array([output[-1]]).reshape((1, 1))
        #print("X",X)
        Y, state = model(X, state)  # 前向计算不需要传入模型参数
        #print("Y",Y)
        #print("state:",state)
        if t < len(prefix) - 1:
            output.append(char_to_idx[prefix[t + 1]])
            #print(char_to_idx[prefix[t + 1]])
        else:
            output.append(int(np.array(tf.argmax(Y,axis=-1))))
            #print(int(np.array(tf.argmax(Y[0],axis=-1))))
    return ''.join([idx_to_char[i] for i in output])

In [16]:
# 没训练之前，输出预测歌词的结果
model = RNNModel(rnn_layer, vocab_size)
predict_rnn_keras('分开', 10, model, vocab_size,  idx_to_char, char_to_idx)

'分开以师欣恨虽钩汹偷留姑'

In [60]:
# 计算裁剪后的梯度 [这里有点复杂，暂时没看]
def grad_clipping(grads,theta):
    norm = np.array([0])
    for i in range(len(grads)):
        norm+=tf.math.reduce_sum(grads[i] ** 2)
    #print("norm",norm)
    norm = np.sqrt(norm).item()
    new_gradient=[]
    if norm > theta:
        for grad in grads:
            new_gradient.append(grad * theta / norm)
    else:
        for grad in grads:
            new_gradient.append(grad)  
    #print("new_gradient",new_gradient)
    return new_gradient

# 训练模型，并预测
def train_and_predict_rnn_keras(model, num_hiddens, vocab_size, 
                                corpus_indices, idx_to_char, char_to_idx,
                                num_epochs, num_steps, lr, clipping_theta,
                                batch_size, pred_period, pred_len, prefixes):
    loss = tf.keras.losses.SparseCategoricalCrossentropy()
    optimizer=tf.keras.optimizers.SGD(learning_rate=lr)
    
    for epoch in range(num_epochs):
        l_sum, n, start = 0.0, 0, time.time()
        data_iter = d2l.data_iter_consecutive(
            corpus_indices, batch_size, num_steps)
        state = model.get_initial_state(batch_size=batch_size,dtype=tf.float32)
        for X, Y in data_iter:
            with tf.GradientTape(persistent=True) as tape:
                (outputs, state) = model(X, state)
                y = Y.T.reshape((-1,))
                l = loss(y,outputs)
            
            grads = tape.gradient(l, model.variables)
            # 梯度裁剪
            grads=grad_clipping(grads, clipping_theta)
            optimizer.apply_gradients(zip(grads, model.variables))  # 因为已经误差取过均值，梯度不用再做平均
            l_sum += np.array(l).item() * len(y)
            n += len(y)

        if (epoch + 1) % pred_period == 0: # 每隔 pred_period个epoch，输出一次预测结果，看看训练效果
            print('epoch %d, perplexity %f, time %.2f sec' % (
                epoch + 1, math.exp(l_sum / n), time.time() - start))
            for prefix in prefixes:
                print(' -', predict_rnn_keras(
                    prefix, pred_len, model, vocab_size,  idx_to_char,
                    char_to_idx))

In [61]:
num_epochs, batch_size, lr, clipping_theta = 250, 32, 1e2, 1e-2
pred_period, pred_len, prefixes = 50, 50, ['分开', '不分开']
train_and_predict_rnn_keras(model, num_hiddens, vocab_size, 
                            corpus_indices, idx_to_char, char_to_idx,
                            num_epochs, num_steps, lr, clipping_theta,
                            batch_size, pred_period, pred_len, prefixes)

epoch 50, perplexity 20753262.117279, time 1.38 sec
 - 分开 的的的著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著
 - 不分开的的著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著著
epoch 100, perplexity 1998656.964821, time 1.35 sec
 - 分开   在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在
 - 不分开  在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在在
epoch 150, perplexity 2944438.390412, time 1.37 sec
 - 分开    让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让
 - 不分开   让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让
epoch 200, perplexity 2944438.390412, time 1.34 sec
 - 分开    让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让
 - 不分开   让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让
epoch 250, perplexity 2944438.390412, time 1.35 sec
 - 分开    让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让
 - 不分开   让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让让


In [ ]:
"""
输出都是同一个字，说明训练效果很差，用gru或lstm可以得到更好的训练效果。
"""